name: comments sample

on: pull_request

jobs:
  comment:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: comment
        run: |
          gh pr comment ${{ github.event.pull_request.number }} -b 'test' --repo ${{ github.repository }}
